FROM node:20-alpine AS backend-prod

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . ./

RUN mkdir -p /app/logs && chown -R node:node /app/logs

USER node
EXPOSE 4000
ENV NODE_ENV=production

CMD ["node", "src/server.js"]
